# This is a basic workflow to help you get started with Actions

name: get_the_watch_list

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "*/1 * * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: https://runewatch.com/api/cases/mixedlist -o watch-list.json
